name: Deploy

on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          version: 10
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Deploy to GitHub Pages
        run: gh-pages --dist public --repo git:${GITHUB_TOKEN}@github.com:colebemis/colebemis.github.io.git --branch master
